'use client';
import {useEffect,useRef,useState} from 'react';
import type * as Three from 'three';
export default function MaterialScene({kind,label,note}:{kind:string,label:string,note:string}){
 const host=useRef<HTMLDivElement>(null);const rotation=useRef(0);const paused=useRef(false);const [isPaused,setPaused]=useState(false);const [failed,setFailed]=useState(false);
 useEffect(()=>{let disposed=false;let cleanup=()=>{};const node=host.current;if(!node)return;const el:HTMLDivElement=node;
 async function init(){try{const T=await import('three');if(disposed)return;const scene=new T.Scene();const camera=new T.PerspectiveCamera(36,1,.1,100);camera.position.set(5,3.1,7);camera.lookAt(0,0,0);const renderer=new T.WebGLRenderer({antialias:true,alpha:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.8));renderer.setClearColor(0,0);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;el.appendChild(renderer.domElement);
 scene.add(new T.AmbientLight(0xdde5d7,2));const key=new T.DirectionalLight(0xfff4d7,5);key.position.set(4,6,4);scene.add(key);const rim=new T.DirectionalLight(0x94bab3,3);rim.position.set(-4,1,-2);scene.add(rim);const group=new T.Group();scene.add(group);
 const mat=(color:number,metalness=.1,roughness=.4)=>new T.MeshStandardMaterial({color,metalness,roughness});
 const add=(geo:Three.BufferGeometry,material:Three.Material,x=0,y=0,z=0)=>{const mesh=new T.Mesh(geo,material);mesh.position.set(x,y,z);group.add(mesh);return mesh};
 const wire=(geo:Three.BufferGeometry,x=0,y=0,z=0,color=0xa9b3a3)=>{const mesh=new T.LineSegments(new T.EdgesGeometry(geo,25),new T.LineBasicMaterial({color,transparent:true,opacity:.26}));mesh.position.set(x,y,z);group.add(mesh);return mesh};
 if(kind==='sulphur'){const gold=mat(0xeabf1c,.15,.32);for(let i=0;i<17;i++){const a=i*2.399;const r=.22*Math.sqrt(i);const h=.65+(Math.sin(i*8.3)+1)*.7;const m=add(new T.CylinderGeometry(.13,.48,h,5),gold,Math.cos(a)*r,-.7+h/2+Math.sin(i)*.15,Math.sin(a)*r);m.rotation.set(Math.cos(i)*.3,a,Math.sin(i)*.35)}group.rotation.z=-.15;}
 else if(kind==='urea'){const pearl=mat(0xf2eee0,.05,.28);for(let i=0;i<94;i++){const a=i*2.399,r=1.35*Math.sqrt(i/94);const y=-.65+1.1*(1-r/1.4)+Math.sin(i*7)*.18;const m=add(new T.SphereGeometry(.14+.04*(1+Math.sin(i)),16,12),pearl,Math.cos(a)*r,y,Math.sin(a)*r);m.scale.set(1,1.1,.9)}}
 else {const metal=mat(kind==='lng'?0x9bafb2:0x898d85,.8,.27);const dark=mat(0x31372e,.5,.35);const accent=mat(kind==='lng'?0x69bfd0:0xa57232,.5,.2);const geo=new T.CylinderGeometry(1.05,1.05,2.5,64,1,true,Math.PI*.3,Math.PI*1.65);add(geo,metal);wire(geo);add(new T.CylinderGeometry(1.05,1.05,.12,64),dark,0,-1.25);const top=add(new T.SphereGeometry(1.05,48,24,0,Math.PI*2,0,Math.PI/2),metal,0,1.25);top.scale.y=.26;add(new T.CylinderGeometry(.86,.86,1.55,48),accent,0,-.4);for(const y of[-1.2,-.8,.7,1.23]){const ring=add(new T.TorusGeometry(1.065,.025,8,60),dark,0,y);ring.rotation.x=Math.PI/2}for(const x of[-.75,.75])for(const z of[-.65,.65])add(new T.CylinderGeometry(.07,.09,.35,10),dark,x,-1.48,z);const pipe=add(new T.CylinderGeometry(.07,.07,1,12),accent,1.3,-.65);pipe.rotation.z=Math.PI/2;wire(new T.BoxGeometry(2.7,3.2,2.7),0,0,0,0x5c7760);group.rotation.y=-.6;}
 const grid=new T.GridHelper(8,20,0x627357,0x344332);grid.position.y=-1.7;const gm=grid.material as Three.Material;gm.transparent=true;gm.opacity=.3;scene.add(grid);
 const resize=()=>{const w=el.clientWidth,h=el.clientHeight;if(!w||!h)return;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();camera.position.z=w/h<.85?9:7};const ro=new ResizeObserver(resize);ro.observe(el);resize();let visible=true;const io=new IntersectionObserver(e=>{visible=e[0].isIntersecting});io.observe(el);const reduce=window.matchMedia('(prefers-reduced-motion: reduce)').matches;paused.current=reduce;setPaused(reduce);let down=false,last=0;const pd=(e:PointerEvent)=>{down=true;last=e.clientX;el.setPointerCapture(e.pointerId)};const pm=(e:PointerEvent)=>{if(down){rotation.current+=(e.clientX-last)*.01;last=e.clientX}};const pu=()=>{down=false};el.addEventListener('pointerdown',pd);el.addEventListener('pointermove',pm);el.addEventListener('pointerup',pu);el.addEventListener('pointercancel',pu);let frame=0;const clock=new T.Clock();const animate=()=>{frame=requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05);if(visible){if(!paused.current&&!down)rotation.current+=dt*.13;group.rotation.y=rotation.current;renderer.render(scene,camera)}};animate();cleanup=()=>{cancelAnimationFrame(frame);ro.disconnect();io.disconnect();el.removeEventListener('pointerdown',pd);el.removeEventListener('pointermove',pm);el.removeEventListener('pointerup',pu);el.removeEventListener('pointercancel',pu);scene.traverse(o=>{const m=o as Three.Mesh;if(m.geometry)m.geometry.dispose();if(m.material){(Array.isArray(m.material)?m.material:[m.material]).forEach(x=>x.dispose())}});renderer.dispose();renderer.domElement.remove()};}catch{if(!disposed)setFailed(true)}}init();return()=>{disposed=true;cleanup()};},[kind]);
 return <div className="scene-wrap"><div ref={host} className="scene" role="img" aria-label={`Interactive three-dimensional ${label.toLowerCase()}`}>{failed&&<div className="fallback">{kind==='sulphur'?'S':kind==='urea'?'N':kind==='lng'?'CH₄':'C'}</div>}</div><div className="scene-top"><span>{label}</span><span>3D</span></div><div className="scene-bottom"><span>{note}</span><span>DRAG TO ROTATE</span></div>{!failed&&<div className="scene-control"><button onClick={()=>rotation.current-=.4} aria-label="Rotate model left">←</button><button onClick={()=>{paused.current=!paused.current;setPaused(paused.current)}} aria-label={isPaused?'Play model rotation':'Pause model rotation'}>{isPaused?'▶':'Ⅱ'}</button><button onClick={()=>rotation.current+=.4} aria-label="Rotate model right">→</button></div>}</div>
}
