'use client';
import {useState,useEffect} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableBody,TableRow,TableCell} from '@/components/ui/table';
import MaterialScene from './material-scene';
import products from './products.json';
type Product=typeof products[number];
const groups=[
 {name:'Metals & minerals',text:'HMS · Copper scrap · Gold · Ferroalloys',items:['Heavy melting steel (HMS) for steelmaking and recycling. Grade, dimensions and contamination limits agreed for each shipment.','Copper scrap, including wire and transformer-derived material. Recovery, purity and insulation content assessed by grade.','Gold enquiries are evaluated against agreed form, fineness, origin and documentation.','Ferro manganese, ferro silicon, silico manganese and ferro chromium for industrial applications.'],symbol:'Fe / Cu'},
 {name:'Carbon & coal',text:'Petroleum coke · Anthracite · Graphite · Metallurgical coke',items:['Calcined petroleum coke, calcined anthracite and carbon raisers for metallurgical applications.','Graphite fines, amorphous graphite, electrode paste and tamping paste for industrial processes.','Coal, metallurgical coke and related carbon materials specified by carbon, ash, sulphur, moisture and size.'],symbol:'C'},
 {name:'Agricultural commodities',text:'Coffee · Copra',items:['Coffee sourcing based on origin, variety, processing, grade, moisture and agreed quality assessment.','Copra for oil extraction and processing. Moisture, oil content, impurities and packing specified for the intended use.'],symbol:'AG'},
 {name:'Recovered materials',text:'Used oil · Recycling feedstocks',items:['Used oil from maritime and industrial sources, assessed for licensed recovery or re-refining.','Used oil is a separate product from crude petroleum. Composition, contaminants and acceptable destination are evaluated for each enquiry.'],symbol:'RE'}
];
const email=(name:string)=>`mailto:sales@benellc.com?subject=${encodeURIComponent('Bene LLC — '+name+' enquiry')}&body=${encodeURIComponent('Hello Bene team,\n\nI would like to discuss '+name+'.\n\nRequired grade / specification:\nQuantity and unit:\nDestination port / terminal:\nDelivery window:\nPacking / shipping requirements:\nCompany and contact details:\n\nThank you.')}`;
export default function BeneSite(){const[detail,setDetail]=useState<Product|null>(null);const[category,setCategory]=useState<typeof groups[number]|null>(null);const[active,setActive]=useState('sulphur');
 useEffect(()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const art=document.querySelector<HTMLElement>('.hero-art');let pending=false;const scroll=()=>{if(pending)return;pending=true;requestAnimationFrame(()=>{pending=false;if(art&&innerWidth>650)art.style.transform=`translateY(${Math.min(scrollY*.13,100)}px) rotate(${Math.min(scrollY*.003,2)}deg)`})};addEventListener('scroll',scroll,{passive:true});return()=>removeEventListener('scroll',scroll)},[]);
 return <><a className="skip" href="#main">Skip to content</a><header className="nav"><div className="shell nav-inner"><a className="brand" href="#main" aria-label="Bene LLC home">bene<span className="brand-dot"/><small>GLOBAL<br/>COMMODITIES</small></a><nav className="navlinks" aria-label="Main navigation"><a href="#commodities">Commodities</a><a href="#about">Our approach</a><a href="#contact">Contact</a></nav><a href={email('commodity trading')} className="cta">Talk trade <span>↗</span></a></div></header>
 <main id="main"><section className="shell hero"><div className="eyebrow"><span className="signal">●</span> Bene LLC / Global commodity trading</div><h1>Materials that<br/>move <em>the world.</em></h1><img className="hero-art" src="/sulfur-hero.webp" width="1536" height="1024" fetchPriority="high" alt="Golden yellow sulphur crystal formation"/><div className="hero-bottom"><p>From essential minerals to the energy of tomorrow. Connecting your business to the materials it needs.</p><a className="text-link" href="#commodities">Explore our commodities <span>↓</span></a></div><div className="material-label"><span>S / SULPHUR</span><span>16</span></div><div className="hero-footer"><span>SOURCING. LOGISTICS. DELIVERY.</span><span>SCROLL TO DISCOVER ↓</span></div></section>
 <div className="shell"><div className="ticker">{['Sulphur','Urea','Crude oil','LNG','Metals & minerals'].map(x=><span key={x}><b>+</b>{x}</span>)}</div></div>
 <section id="commodities" className="dark-section"><div className="shell"><div className="section-top"><div><span className="eyebrow">01 / Essential commodities</span><h2>Different materials.<br/>One trading partner.</h2></div><p>Sourcing for agriculture, industry and energy. Explore the materials at the heart of our trading portfolio.</p></div>
 <Tabs className="product-tabs" value={active} onValueChange={v=>setActive(String(v))}><TabsList aria-label="Explore commodities">{products.map(p=><TabsTrigger key={p.id} value={p.id}><span>{p.name}</span><span className="tab-num">{p.number} ↗</span></TabsTrigger>)}</TabsList>{products.map(p=><TabsContent key={p.id} value={p.id}><div className="explorer"><MaterialScene key={p.id} kind={p.id} label={p.modelLabel} note={p.modelNote}/><div className="product-copy"><span className="eyebrow">{p.category}</span><h3>{p.name}</h3><p>{p.description}</p><dl className="specs">{p.highlights.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><p className="fine">{p.note}</p><div className="product-actions"><a className="cta" href={email(p.name)}>Enquire about {p.name.toLowerCase()} <span>↗</span></a><button className="outline-btn" onClick={()=>setDetail(p)}>Product details +</button></div></div></div></TabsContent>)}</Tabs></div></section>
 <section className="shell portfolio" id="portfolio"><div className="section-top"><div><span className="eyebrow">02 / Our wider portfolio</span><h2>Across industries.<br/>Beyond borders.</h2></div><p>Established materials and emerging requirements, brought together through one coordinated sourcing relationship.</p></div><div className="portfolio-list">{groups.map((g,i)=><button key={g.name} className="portfolio-row" onClick={()=>setCategory(g)}><span className="eyebrow">0{i+1}</span><h3>{g.name}</h3><p>{g.text}</p><span className="arrow">↗</span></button>)}</div></section>
 <section className="process" id="about"><div className="shell"><div className="section-top"><div><span className="eyebrow">03 / The Bene approach</span><h2>From your requirement.<br/>To your destination.</h2></div><p>Bene LLC brings commodity sourcing, trade coordination and logistics into one conversation. Every engagement starts with the material and the outcome you need.</p></div><div className="process-grid">{[['01','Define the requirement','Tell us the grade, quantity, destination and delivery window. We align the sourcing brief with your commercial and technical needs.'],['02','Structure the supply','Evaluate the source, agreed specifications and commercial terms. Plan documentation and inspection around the transaction.'],['03','Coordinate delivery','Bring shipment planning and counterpart communication together, with handling and delivery requirements agreed for your cargo.']].map(([n,t,d])=><article key={n}><span className="eyebrow">{n} ───── ↗</span><h3>{t}</h3><p>{d}</p></article>)}</div><div className="approach-note"><span className="eyebrow">A considered approach</span><p>Clear specifications, appropriate handling and transparent documentation help build dependable trading relationships.</p></div></div></section>
 <section className="shell contact" id="contact"><span className="eyebrow">04 / Start a conversation</span><div className="contact-inner"><div><h2>Your next shipment<br/>starts here.</h2><a className="mail-link" href="mailto:sales@benellc.com">sales@benellc.com <span>↗</span></a></div><div><p>Share your product, quantity, destination and timeline. Let’s discuss the supply that works for your business.</p><a className="cta" href={email('commodity trading')}>Discuss your requirements <span>↗</span></a></div></div></section>
 </main><div className="shell"><footer className="footer"><a className="brand" href="#main">bene<span className="brand-dot"/></a><span>© {new Date().getFullYear()} Bene LLC</span><nav className="footer-nav" aria-label="Footer"><a href="#commodities">Commodities</a><a href="#about">Our approach</a><a href="mailto:info@benellc.com">General enquiries ↗</a></nav></footer></div>
 <Dialog open={!!detail} onOpenChange={o=>{if(!o)setDetail(null)}}><DialogContent className="detail-modal">{detail&&<><span className="eyebrow">Bene LLC / {detail.category}</span><DialogTitle>{detail.name}</DialogTitle><DialogDescription>{detail.tagline}</DialogDescription><p>{detail.description}</p><h3>Product & commercial specification</h3><Table><TableBody>{detail.specs.map(([k,v])=><TableRow key={k}><TableCell className="spec-key">{k}</TableCell><TableCell>{v}</TableCell></TableRow>)}</TableBody></Table><h3>Applications</h3><ul>{detail.applications.map(x=><li key={x}>{x}</li>)}</ul><h3>What to include in your enquiry</h3><p>{detail.enquiry}</p><p className="detail-note">{detail.note}</p><a className="cta" href={email(detail.name)}>Enquire about {detail.name.toLowerCase()} <span>↗</span></a><details className="source-details"><summary>Product references</summary>{detail.sources.map(([t,u])=><a className="source-link" href={u} target="_blank" rel="noreferrer" key={u}>{t} ↗</a>)}</details></>}</DialogContent></Dialog>
 <Dialog open={!!category} onOpenChange={o=>{if(!o)setCategory(null)}}><DialogContent className="detail-modal">{category&&<><span className="eyebrow">Bene LLC / Wider portfolio</span><DialogTitle>{category.name}</DialogTitle><DialogDescription>{category.text}</DialogDescription>{category.items.map(x=><p key={x}>{x}</p>)}<p className="detail-note">Supply, specifications and delivery are agreed for each transaction.</p><a className="cta" href={email(category.name)}>Discuss your requirement <span>↗</span></a></>}</DialogContent></Dialog>
 </>
}
